sudo: false

language: java

services:
  - docker

jdk:
  - openjdk8
  - oraclejdk8

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 opendxl/opendxl-broker
  - docker ps -a

script:
  - java -jar ./build/libs/dxlclient*all.jar provisionconfig clientconfig 127.0.0.1 client -u admin -p password
  - sed -i -e "s/127.0.0.1;127.0.0.1/127.0.0.1/g" -e "/local/d" -e "/docker/d" clientconfig/dxlclient.config
  - cat clientconfig/dxlclient.config
  - echo Running tests with MQTT
  - ./gradlew test --info --console=plain
  - sed -i -e "s/= false/= true/g" -e "s/;8883/;443/g" -e "s/Brokers/BrokersWebSockets/g"  clientconfig/dxlclient.config
  - cat clientconfig/dxlclient.config
  - echo Running tests with WebSockets
  - ./gradlew cleanTest test --info --console=plain
