sudo: false

language: java

services:
  - docker

jdk:
  - oraclejdk8

python:
  - "2.7"

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 opendxl/opendxl-broker
  - docker ps -a

before_script:
  - pip install --user dxlclient
  - python -m dxlclient provisionconfig clientconfig 127.0.0.1 client -u admin -p password
  - sed -i -e "s/127.0.0.1;127.0.0.1/127.0.0.1/g" -e "/local/d" -e "/docker/d" clientconfig/dxlclient.config
  - cat clientconfig/dxlclient.config

script:
  - ./gradlew test --info